### PR TITLE
Update Package.swift to support 4.2

### PR DESCRIPTION
**Pull request by shkhaliq**
I am building a personal project [here](https://github.com/shkhaliq/automatic-branch-merging). I want to use octokit but realized it doesn't have support for SwiftPM. 
I am updating the RequestKit PM to  Swift 4.2 and have a subsequent PR for octokit thats ready to [go](https://github.com/nerdishbynature/octokit.swift/compare/master...shkhaliq:add-package-manager?expand=1) to add support for Swift PM

Some of the xcodeproj files got updated after I ran generate-xcodeproj but I decided not to include those.

### CODE REVIEW

**Comment by shkhaliq** [comment]
Looks like Travis is failing and it's dependent on https://github.com/nerdishbynature/RequestKit/pull/56.

Now that Xcode 10 GM is live, we can merge that.

**Comment by pietbrauer** [comment]
@shkhaliq Could you rebase onto the master? Thanks.

**Comment by ghost** [comment]
@pietbrauer done

**Comment by pietbrauer** [comment]
Thanks!

**Pull request merged**
