### PR TITLE
Swift 4.2 Support

### PR DESCRIPTION
**Pull request by tiferrei**

### CODE REVIEW

**Comment by tiferrei** [comment]
@pietbrauer in terms of compatibility this is basically it. Are there any changes or improvements we'd like to do with the new Swift version?

PS: Let's keep this PR open until Xcode 10 is released. Further Swift 4.2 API changes are expected due to ongoing feedback from the Xcode 10 Betas.

**Comment by pietbrauer** [comment]
Sounds good to me.

**Comment by shkhaliq** [comment]
FYI

https://github.com/nerdishbynature/RequestKit/pull/58#issuecomment-429596413

**Comment by pietbrauer** [comment]
Closed via #59

**Pull request closed without merging**
