### PR TITLE
Updated Gemfile dependencies

### PR DESCRIPTION
**Pull request by tiferrei**
The tests are failing the same way TanukiKit was when I tried to do the merge requests, same errors really. This fixed it.

Tiago

### CODE REVIEW

**Comment by pietbrauer** [comment]
👌

**Comment by tiferrei** [comment]
BTW, can we make a branch for a `swift3` version and another for a `swift2.3` version? Both for `RequestKit` and `TanukiKit`? Seems to be the best approach as they are both being used for now.

**Comment by pietbrauer** [comment]
There is a swift-2.3 branch

**Comment by tiferrei** [comment]
Yes, but what's the strategy?

A: Master is swift3, and another branch for 2.3
B: No master, one branch for swift3, another for 2.3
C: 2.3 will be merged into master and separate one for swift3 will be created

**Comment by pietbrauer** [comment]
Master stays Swift 2, all pull requests are on Swift 2, vackports to `swift-2.3` and `swift-3` branch.

Because you can release software from beta Xcode master has to stay Swift 2.

**Comment by tiferrei** [comment]
Cool, so would you like to create a `swift-3` branch from master and I could take care of the swift3 part and do a pull request?

**Comment by pietbrauer** [comment]
Yes, I will do one later today or tomorrow. You can work from your fork if you need something urgent.

**Comment by tiferrei** [comment]
Yup, will create a `swift3-dev` on my forked version. Thanks!

**Pull request merged**
