### PR TITLE
Add capability to setup request tracing

### PR DESCRIPTION
**Pull request by niamster**
Example output:
```
2022-01-07 19:28:22 / E5F8826D:  URL https://api.github.com/notifications?all=false&page=1&participating=true&per_page=20
2022-01-07 19:28:22 / E5F8826D:  Request header: Authorization -> token foobarfoobar
2022-01-07 19:28:22 / E5F8826D:  Request header: Cache-Control -> no-cache
2022-01-07 19:28:22 / E5F8826D:  Response header: Access-Control-Allow-Origin -> Optional("*")
2022-01-07 19:28:22 / E5F8826D:  Response header: access-control-expose-headers -> Optional("ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset")
2022-01-07 19:28:22 / E5F8826D:  Response header: Cache-Control -> Optional("private, max-age=60, s-maxage=60")
2022-01-07 19:28:22 / E5F8826D:  Response header: Content-Encoding -> Optional("gzip")
2022-01-07 19:28:22 / E5F8826D:  Response header: content-security-policy -> Optional("default-src \'none\'")
2022-01-07 19:28:22 / E5F8826D:  Response header: Content-Type -> Optional("application/json; charset=utf-8")
2022-01-07 19:28:22 / E5F8826D:  Response header: Date -> Optional("Fri, 07 Jan 2022 18:28:22 GMT")
2022-01-07 19:28:22 / E5F8826D:  Response header: Etag -> Optional("W/\"\"")
2022-01-07 19:28:22 / E5F8826D:  Response header: Last-Modified -> Optional("Fri, 07 Jan 2022 18:23:15 GMT")
2022-01-07 19:28:22 / E5F8826D:  Response header: referrer-policy -> Optional("origin-when-cross-origin, strict-origin-when-cross-origin")
2022-01-07 19:28:22 / E5F8826D:  Response header: Server -> Optional("GitHub.com")
```

### CODE REVIEW

**Comment by niamster** [comment]
I think I have to add new file to the `XCode` project 🤔  

Screenshot

Screenshot

**Comment by pietbrauer** [comment]
Not sure how I feel about this functionality in RequestKit especially littering the console with response headers which, most of the time, are only interesting in very specific cases.

To make this complete it would be nice to log the response information like size and status code and have the response headers optionally.

I know you are fighting with GitHub cache at the moment but I don’t think a lot of people are facing the same thing using this library.

I usually use tools like Proxyman, Charles or Instruments when I need to debug requests so this functionality would only be half baked at best for most people.

**Comment by niamster** [comment]
@pietbrauer I understand that this is not a great way to debug but, unfortunately, I couldn't find any free tool that could be helpful and Instruments does not support this feature for macOS older than v12.
I agree that printing to the stdout is not great although I didn't want to make things too complicated either (at least for the start). 
I will think a little bit on whether  this could be transformed into something more solid or I can just close this PR as soon as I migrate to new osX version :).

**Comment by niamster** [comment]
Closing for now as I'm not having a lot of time for this one.

**Pull request closed without merging**
