### PR TITLE
[WIP] Swift Package Manager Support

### PR DESCRIPTION
**Pull request by tiferrei**
Now that Swift PM has reached v4.0 it is stable enough to be implemented.
This is a work in progress.

### CODE REVIEW

**Comment by tiferrei** [comment]
@pietbrauer any idea what's up with Xcode 9.3? The source and CI are the same, just updated Xcode to check if the errors were only on my side.

**Comment by pietbrauer** [comment]
@tiferrei Please see #53. Unfortunately upgrading Xcode is a bit more work than just changing the base image of Travis 🙂

**Comment by tiferrei** [comment]
@pietbrauer perfect, thanks! I'll rollback to the previous commit so that we can merge this.

**Comment by pietbrauer** [comment]
You could also rebase on master after #53 is merged.

**Comment by tiferrei** [comment]
@pietbrauer yeah, it just seems more organised to make sure this PR is only for the Package Manager stuff.

**Comment by tiferrei** [comment]
Just tested this locally, all good. 👍

**Comment by tiferrei** [comment]
Swift PM requires the manifest to be part of the release, so the previous releases don't have PM support, we'd have to draft a new (probably minor like 2.2.1) release to add support.

**Pull request merged**
