### PR TITLE
Xcode 10.2 and Swift 5

### PR DESCRIPTION
**Pull request by tiferrei**
Not much changed. ABI stability is a great thing. :)

### CODE REVIEW

**Comment by pietbrauer** [comment]
Hey, thanks for the PR. I think the travis file should be updated as well (when they are ready).

**Comment by tiferrei** [comment]
Indeed,  hopefully they'll add Xcode 10.2 soon. Marking this as WIP meanwhile.

**Comment by rubiojr** [comment]
Today! https://blog.travis-ci.com/2019-03-29-xcode-10-2-gm-is-now-available

**Comment by pietbrauer** [comment]
@tiferrei Could you use the new Xcode version so we can get this merged? If not, I am also happy to do it tomorrow.

**Comment by tiferrei** [comment]
I don't follow what's wrong with the CI. Says `5.0 has been installed.` but returns an error code.

**Comment by pietbrauer** [comment]
The `bundler` error is gone now. Now it's `error: SDK "iphonesimulator12.0" cannot be located.` which should be easy to fix.

**Pull request merged**
