### PR TITLE
Xcode 10.2 and Swift 5.1

### PR DESCRIPTION
**Pull request by JosephDuffy**
I have branched off of https://github.com/nerdishbynature/RequestKit/pull/63 to (hopefully) fix CI, and add support for Swift 5.1 on Linux (by importing `FoundationNetworking`, as per https://forums.swift.org/t/foundationnetworking/24769)

### CODE REVIEW

**Comment by f-meloni** [comment]
Hey I would like to help with this PR, I need this for Danger as well, is there something I can do to help this PR to get merged?

**Comment by pietbrauer** [comment]
@f-meloni I waited a long time but seems that this is not moving forward.

I would definitely take what @JosephDuffy has already done and move everything straight to Swift 5.1 and Xcode 11 on Travis.

**Review by pietbrauer — APPROVED** [review]

**Comment by pietbrauer** [comment]
Hah, seems I was super confused by the WIP plugin and thought the build was failing. Sorry about that. Thanks a lot @JosephDuffy!

@f-meloni do you need more for danger else I would make a release?

**Comment by f-meloni** [comment]
I think this should be ok!
Thank you very much @pietbrauer 🚀

**Comment by f-meloni** [comment]
Hey @pietbrauer did you release a new version of RequestKit?

**Comment by pietbrauer** [comment]
@f-meloni I did now, yes.

**Comment by f-meloni** [comment]
Thank you very much :)

**Pull request merged**
