### PR TITLE
Update URLSession.shared API

### PR DESCRIPTION
**Pull request by phatblat**
Changed in Xcode 8 beta 2

### CODE REVIEW

**Comment by pietbrauer** [comment]
Tests failed because you forgot to change the API usage in [RequestKitTests/TestInterface](https://github.com/nerdishbynature/RequestKit/blob/swift-3.0/RequestKitTests/TestInterface.swift#L18).

**Comment by phatblat** [comment]
Oops! Fixed now.

**Comment by pietbrauer** [comment]
Thanks :+1:

**Comment by phatblat** [comment]
Does the fact that this built successfully mean that Travis is now using Xcode 8 beta 2?

**Comment by pietbrauer** [comment]
Yes, they updated.

**Pull request merged**
